### ISSUE TITLE
Ping-Pong ArrayChannels example: preload.jl does not exist

### ISSUE THREAD

**Issue by jpsamaroo** [rohanmclure/ArrayChannels.jl#6]
The file `example/ping_pong_array_channels.jl` references a file called "preload.jl", which does not exist in the repository. I assume it intended to reference `src/precompile.jl`? If so, you should probably reference the file relative to the current script's path, like: `include(joinpath(@__DIR__, "..", "src", "precompile.jl"))`. However, I've noticed that you also include `precompile.jl` as part of package initialization, so I guess this invocation isn't needed at all?

**Comment by rohanmclure** [comment]
Apologies, `preload.jl` was how you installed the package in previous versions. I've now removed that line.
